apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-executor
  labels:
    app: orion-executor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion-executor
  template:
    metadata:
      labels:
        app: orion-executor
    spec:
      containers:
      - name: executor
        image: 2000023946/orion-executor:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
            name: grpc
          - containerPort: 8000
            name: metrics
        env:
        - name: METADATA_DB_URL
          value: "mongodb://orion-mongodb:27017"
        - name: EMBEDDING_TARGET_ADDRESS
          value: "http://orion-embedding:80"
        - name: QDRANT_TARGET_ADDRESS
          value: "http://orion-qdrant:6333"
          
        # ==========================================
        # MOCK KEYS: Prevents Python KeyErrors on boot
        # ==========================================
        - name: LLM_API_KEY
          value: "mock_llm_key_local_testing"
        - name: WEB_API_KEY
          value: "mock_web_key_local_testing"
        - name: BUS_TARGET_ADDRESS
          value: "redis://orion-redis:6379/0"
        resources:
          requests:
            cpu: "1"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: orion-executor
spec:
  selector:
    app: orion-executor
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: orion-executor-scaler
  labels:
    app: orion-executor
spec:
  scaleTargetRef:
    # Must match the name of your apps/v1 Deployment
    name: orion-executor
  minReplicaCount: 1
  # Capped at 4 to prevent your local macOS Minikube environment from locking up under heavy load testing
  maxReplicaCount: 3
  pollingInterval: 3
  cooldownPeriod: 60
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.default.svc.cluster.local:9090
      
      # An internal name KEDA uses to register the metric with the HPA
      metricName: orion_queue_depth_keda
      
      # Use the exact working query from your python script
      # The '|' character ensures the query is passed as a raw string
      query: |
        sum(max_over_time(redis_key_size{key="queue:search_tasks"}[30s]))
        
      threshold: "5"