# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\rgraphexecutor\"R\n\x10\x45xecutionRequest\x12\x12\n\nquery_text\x18\x01 \x01(\t\x12*\n\x04plan\x18\x02 \x01(\x0b\x32\x1c.graphexecutor.RetrievalPlan\"7\n\rRetrievalPlan\x12&\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x17.graphexecutor.ToolEdge\"&\n\x08ToolEdge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\"<\n\x11\x45xecutionResponse\x12\'\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x16.graphexecutor.Context\"f\n\x07\x43ontext\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .graphexecutor.Context.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32j\n\x14GraphExecutorService\x12R\n\x0b\x45xecutePlan\x12\x1f.graphexecutor.ExecutionRequest\x1a .graphexecutor.ExecutionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTEXT_DATAENTRY']._loaded_options = None
  _globals['_CONTEXT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_EXECUTIONREQUEST']._serialized_start=33
  _globals['_EXECUTIONREQUEST']._serialized_end=115
  _globals['_RETRIEVALPLAN']._serialized_start=117
  _globals['_RETRIEVALPLAN']._serialized_end=172
  _globals['_TOOLEDGE']._serialized_start=174
  _globals['_TOOLEDGE']._serialized_end=212
  _globals['_EXECUTIONRESPONSE']._serialized_start=214
  _globals['_EXECUTIONRESPONSE']._serialized_end=274
  _globals['_CONTEXT']._serialized_start=276
  _globals['_CONTEXT']._serialized_end=378
  _globals['_CONTEXT_DATAENTRY']._serialized_start=335
  _globals['_CONTEXT_DATAENTRY']._serialized_end=378
  _globals['_GRAPHEXECUTORSERVICE']._serialized_start=380
  _globals['_GRAPHEXECUTORSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
